module.exports = {
    AuthController: require('./AuthController'),
    UserController: require('./UserController'),
    UserAddressController: require('./UserAddressController'),
    WishlistController: require('./WishlistController'),
    FaqController: require('./FaqController'),
    CmsController: require('./CmsController'),
    NewsletterController: require('./NewsletterController'),
    SiteSettingController: require('./SiteSettingController'),
    DepartmentController: require('./DepartmentController'),
    ContactUsController: require('./ContactUsController'),
    CategoryController: require('./CategoryController'),
    ProductController: require('./ProductController'),
    ProductReviewController: require('./ProductReviewController'),
    ProductRatingController: require('./ProductRatingController'),
    ProductAttributeController: require('./ProductAttributeController'),
    CartController: require('./CartController'),
    OrderController: require('./OrderController'),
    CouponController: require('./CouponController'),
	RazorPayController : require('./RazorPayController')
};