module.exports = {
    ResponseService: require('./ResponseService'),
    UserService: require('./UserService'),
    UserAddressService: require('./UserAddressService'),
    WishlistService: require('./WishlistService'),
    FaqService: require('./FaqService'),
    CmsService: require('./CmsService'),
    NewsLetterSubscriptionService: require('./NewsLetterSubscriptionService'),
    MailService: require('./MailService'),
    FailedMailService: require('./FailedMailService'),
    SiteSettingService: require('./SiteSettingService'),
    DepartmentService: require('./DepartmentService'), 
    CategoryService: require('./CategoryService'),
    ProductService: require('./ProductService'),
    ProductReviewService: require('./ProductReviewService'),
    ProductRatingService: require('./ProductRatingService'),
    ProductAttributeService: require('./ProductAttributeService'),
    CartService: require('./CartService'),
    OrderService: require('./OrderService'),
    CouponService: require('./CouponService'),
};